spring.application.name=migration-service-rest

server.port=8081

spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/xe
spring.datasource.username=ventas
spring.datasource.password=14693701
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.maximum-pool-size=5
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Eureka Client
eureka.client.service-url.default-zone=http://eureka:password@localhost:8761/eureka
eureka.instance.instance-id=${spring.application.name}:${spring.application.instance_id:${random.value}}
logging.pattern.level= %5p [${spring.application.name}, %X{traceId:-}, %X{spanId:-}]